### PR TITLE
Create fabric-guide.md

### PR DESCRIPTION
**Pull request by ghost**
# Information

- [ ] Fixes a typo.
- [ ] Fixes misinformation.
- [x] Adds a new general article.
- [ ] Adds an article about a plugin. (or adds a plugin to the index)

# Motivation
Adds a barebones article on Fabric as the server software, and lists a few mods that could be potentially useful.
It might be a bit different to what the article should be, but it's what it is.

### CODE REVIEW

**Comment by ukdaaan** [comment]
give us a shout when it's ready for review @HyperSoop

**Comment by ghost** [comment]
> give us a shout when it's ready for review @HyperSoop

it is ready for review, but i think it's a bit more than the article was supposed to cover

**Comment by ghost** [comment]
wait i fucked up!

**Comment by ghost** [comment]
well github won't let me unedit the file that was not supposed to go in that branch, i can't do anything i guess

**Comment by ghost** [comment]
Well, i guess this is not happening. Just ignore the extra changed file?... plz

**Review by ukdaaan — APPROVED** [review]
LGTM

**Pull request merged**
