### PR TITLE
Startup scripts

### PR DESCRIPTION
**Pull request by ghost**
# Information

- [ ] Fixes a typo.
- [x] Fixes misinformation.
- [x] Adds a new general article.
- [ ] Adds an article about a plugin. (or adds a plugin to the index)

# Motivation
Adds a somewhat proper startup scripts article, describing a few basic options, linking to a good perfomance JVM flag set collection and listing the Minecraft startup flags.

### CODE REVIEW

**Comment by ukdaaan** [comment]
hey @HyperSoop how's this page coming along, need anything from us or is all ok?

**Comment by ghost** [comment]
> hey @HyperSoop how's this page coming along, need anything from us or is all ok?

I think it's fine to merge, but i'll have to fix whatever makes it unhappy here (weird, i don't see anything wrong, but i just synced it, it may have been that)
I'm a little worried if the article i made is a little bit too in-depth so it's a bit out of scope and can confuse users, could you please give your opinion on this?

**Review by ukdaaan — CHANGES_REQUESTED** [review]
Happy with the depth,

I'd probably remove the 'mojang internal' flag (think it was the universal one) and right at the end

'The name of the world folder in which the level.dat resides.' doesn't have a flag

apart from that happy to approve :)

**Comment by ghost** [comment]
I removed the "mojang internal" information, also you may have been reading it wrong - it's first flag, then description. 

There is some conflict here now, I can't sync it.

**Pull request merged**
